name = "PCRE2_jll"
uuid = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"
version = "10.34.0+0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
